import MyContextComponents from "@/context/myContext";
import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "Portfolio Indra John",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-9PM69CL8XL" />
      <Script id="google-analytics">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-9PM69CL8XL');
        `}
      </Script>
      <body>
        <MyContextComponents> {children}</MyContextComponents>
      </body>
    </html>
  );
}
