import MyContextComponents from "@/context/myContext";
import "./globals.css";

export const metadata = {
  title: "Portfolio Indra John",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MyContextComponents> {children}</MyContextComponents>
      </body>
    </html>
  );
}
